### ISSUE TITLE
Can't get the color option to work

### ISSUE THREAD

**Issue by visarn** [ryanbaumann/mapboxgl-powerBI#4]
@ryanbaumann 
I am trying out your mapbox for power bi visualization right now, and I can't differentiate the color between two type of location
How can I prepare the data or make the two color point different?

I have attached a sample data set with screen shot
<img width="960" alt="sample screen" src="https://user-images.githubusercontent.com/29891826/30414496-1a11680a-994e-11e7-8c2f-01c83e9c5d00.png">

[Sample Data.xlsx](https://github.com/ryanbaumann/mapboxgl-powerBI/files/1301885/Sample.Data.xlsx)

**Comment by visarn** [comment]
Tooltip does not seems to be working also

**Comment by ryanbaumann** [comment]
Thanks for the ticket, sample data, details @visarn!

It looks like your `color` data, column `Location Type` is a string.  In the current version of the Mapbox + PowerBI beta, color ramps are only calculated for numeric continuous values.  I'm working on this in a new PR now.

**Comment by visarn** [comment]
@ryanbaumann 
Thanks for a quick reply. I was wondering if you could check on the tooltip as well it does not seems to be working.
Thank you

**Comment by ryanbaumann** [comment]
@visarn I added support for acategorical colora in the latest master branch push - try updating the custom visual file in the /dist folder and let me know if that works!

Also added a basic legend.  Color palette, base map, and circle radius measure options coming soon.

**Comment by visarn** [comment]
@ryanbaumann Thank you! Circle radius measure would definitely be useful

**Comment by visarn** [comment]
@ryanbaumann The new release seems to be working Thank you. Just wondering, you did removed the tooltip?

**Comment by ryanbaumann** [comment]
@visarn yes, I did remove the tooltip for now - it wasn't functioning in the current implementation.  Planning to make a much nicer looking HTML formatted popup next.

Thanks for logging the issue!

**Comment by visarn** [comment]
@ryanbaumann Great! looking forward to it.
